import "pkg:/source/RequestExecutorV2.bs"

sub init()
  executorV2().observeField("isInitialized", "loadTest")
end sub

sub loadTest()
  for i = 1 to 50
    executorV2().enqueuePost(createGoogleTranslateRequest())
  endfor
end sub

function createGoogleTranslateRequest()
  request = CreateObject("roSGNode", "Request")
  request.headers= { "Content-Type": "application/json" }
  request.body = { user: "you", password: "123" }
  return request
end function