import "pkg:/source/RequestExecutorV2.bs"

sub init()
  executorV2().observeField("isInitialized", "loadTest")
end sub

sub loadTest()
  for i = 1 to 50
    executorV2().enqueuePost(createPostRequest())
  endfor
end sub

function createPostRequest()
  request = CreateObject("roSGNode", "Request")
  request.headers= { "Content-Type": "application/json" }
  request.body = { randomNumber: StrI(Rnd(55) * 100) }
  return request
end function